### PR TITLE
Contributing

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by zkessin** [comment]
Can you resubmit this vs the open-triq repo

**Comment by tuncer** [comment]
Done.

**Comment by zkessin** [comment]
Thanks, it was merged

**Comment by ghost** [comment]
@krestenkrab?

**Comment by ghost** [comment]
@krestenkrab, ping?

**Comment by ghost** [comment]
Merged to https://github.com/triqng/triq, closing.

**Pull request closed without merging**
