### PR TITLE
19.0 compatibility: introduce and use compat random number module

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tuncer** [comment]
Tested with 18.3.3 and 19.0.2.

**Comment by jj1bdx** [comment]
@tuncer `rand_compat` looks ok, though if no explicit seeding is needed, just use `rand:seed(exsplus)`. See https://github.com/rebar/rebar/pull/612#issuecomment-234956773 for the details. Note: this is _not_ applicable to `random:seed/1`.

**Comment by luc-tielen** [comment]
Looks good but CI failed? Or is this just a flaky unit test?

**Comment by ghost** [comment]
Let's trigger a retest...

**Comment by ghost** [comment]
@jj1bdx, yeah, that could make sense, but let's get the compat fix in and tackle that later.

**Comment by ghost** [comment]
@krestenkrab, ping?

**Comment by alakra** [comment]
👍

**Comment by nippysaurus** [comment]
LGTM. Only issue if the following error during compilation:

```
Error evaluating Rebar config script ./rebar.config.script:13: evaluation failed with reason error:{badmatch,{error,{already_started,crypto}}} and stacktrace [{erl_eval,expr,3,[]}]
Any dependencies defined in the script won't be available unless you add them to your Mix project
```

**Comment by ghost** [comment]
@nippysaurus, good catch, pushed a fix.

**Comment by ghost** [comment]
Merged to https://github.com/triqng/triq, closing.

**Pull request closed without merging**
